server:
  port: 4550
  shutdown: "graceful"

# If you use a database then uncomment the `group:, readiness: and include: "db"` lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "always"
      # group:
      #  readiness:
      #   include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

cqrs:
  client:
    base-url: ${CPP_CAR_URL:http://localhost:8080}
    connect-timeout-ms: ${CPP_CAR_CQRS_CONNECTION_TIMEOUT_MS:3000}
    read-timeout-ms: ${CPP_CAR_CQRS_READ_TIMEOUT_MS:15000}
    headers:
      cjs-cppuid: ${CPP_CAR_CJSCPPUID_HEADER:CJSCPPUID}
    progression:
      accept-header: "application/vnd.progression.query.material-bulk+json"
      material-path: "/progression-query-api/query/api/rest/progression/materials/cases"
    user-groups:
      accept-header: "application/vnd.usersgroups.search-users+json"
      user-group-path: "/usersgroups-query-api/query/api/rest/usersgroups/users"
    system-id-mappers:
      accept-header: "application/vnd.systemid.mappings+json"
      system-id-path: "/system-id-mapper-api/rest/systemid/mappings/bulk"

springdoc:
  packagesToScan: uk.gov.hmcts.cpp.audit.bff.controllers
  writer-with-order-by-keys: true

spring:
  application:
    name: Audit Bff Application

azure:
  fabric:
    subscription-id: ${AZURE_SUBSCRIPTION_ID:your-subscription-id}
    resource-group-name: ${AZURE_RESOURCE_GROUP_NAME:your-resource-group-name}
    fabric-base-url: ${AZURE_FABRIC_BASE_URL:https://api.fabric.microsoft.com/v1}
    workspace-id: ${AZURE_FABRIC_WORKSPACE_ID:}
    pipeline-id: ${AZURE_FABRIC_PIPELINE_ID:}
    pipeline-name: ${AZURE_FABRIC_PIPELINE_NAME:Param Test}
  application-insights:
    instrumentation-key: ${rpe.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
